// flow-typed signature: 0d46b4445d3c8da7fca947631e80232c
// flow-typed version: <<STUB>>/postcss-load-config_v^2.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-load-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-load-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-load-config/src/index' {
  declare module.exports: any;
}

declare module 'postcss-load-config/src/options' {
  declare module.exports: any;
}

declare module 'postcss-load-config/src/plugins' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-load-config/src/index.js' {
  declare module.exports: $Exports<'postcss-load-config/src/index'>;
}
declare module 'postcss-load-config/src/options.js' {
  declare module.exports: $Exports<'postcss-load-config/src/options'>;
}
declare module 'postcss-load-config/src/plugins.js' {
  declare module.exports: $Exports<'postcss-load-config/src/plugins'>;
}
