// flow-typed signature: b4a33cf3b1f0122eb759de0a44c81d42
// flow-typed version: <<STUB>>/prettier-loader_v^2.1.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-loader/__tests__/index' {
  declare module.exports: any;
}

declare module 'prettier-loader/prettier-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-loader/__tests__/index.js' {
  declare module.exports: $Exports<'prettier-loader/__tests__/index'>;
}
declare module 'prettier-loader/index' {
  declare module.exports: $Exports<'prettier-loader'>;
}
declare module 'prettier-loader/index.js' {
  declare module.exports: $Exports<'prettier-loader'>;
}
declare module 'prettier-loader/prettier-loader.js' {
  declare module.exports: $Exports<'prettier-loader/prettier-loader'>;
}
